### ISSUE TITLE
Chip Invisible

### ISSUE THREAD

**Issue by RussiaGo** [drewcifer/bot-topia#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Minecraft (please complete the following information):**
 
 - Version [e.g. 1.16]

**Bot-Topia**
- Version [e.g. 1.0.6]

**Additional context**
Hello I Have A Bug The Chip Invisble Pls Fix It Thx

**Comment by drewcifer** [comment]
what version of bot-topia do you have installed?

**Comment by drewcifer** [comment]
What version of bot-topia do you have installed?

**Comment by RussiaGo** [comment]
1.16.200

**Comment by drewcifer** [comment]
Try uninstalling the add pack. and install the [behavior](https://github.com/drewcifer/bot-topia/releases/download/v1.0.6/BP.Bot-Topia.mcpack) pack and the [resource pack](https://github.com/drewcifer/bot-topia/releases/download/v1.0.6/RP.Bot-Topia.mcpack) separately.

https://github.com/drewcifer/bot-topia/releases/download/v1.0.6/BP.Bot-Topia.mcpack
https://github.com/drewcifer/bot-topia/releases/download/v1.0.6/RP.Bot-Topia.mcpack

make sure they are both enabled.
