### ISSUE TITLE
Chip Invisible

### ISSUE THREAD

**Issue by RussiaGo** [drewcifer/bot-topia#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Minecraft (please complete the following information):**
 
 - Version [e.g. 1.16]

**Bot-Topia**
- Version [e.g. 1.0.6]

**Additional context**
Hello I Have A Bug The Chip Is Invisible Idk How pls Fix This Thank You.

**Comment by drewcifer** [comment]
duplicate issue
https://github.com/drewcifer/bot-topia/issues/3
