### ISSUE TITLE
Broken install for Xbox. 

### ISSUE THREAD

**Issue by crotin1111** [drewcifer/bot-topia#5]
**Describe the bug**

**To Reproduce**
1. Go to 'mc add-on manager (Xbox)'
2. Click on 'import''
3. See error

**Expected behavior**
Should usually work I guess

**Screenshots**

**Minecraft (please complete the following information):**
 
 - Version [e.g. 1.16]
 - latest
**Bot-Topia**
- Version [e.g. 1.0.6]
Latest
**Additional context**
![Snapchat-1257918182](https://user-images.githubusercontent.com/10578031/105643095-e6136e00-5e5b-11eb-9999-4d4f829a86c1.jpg)

**Comment by drewcifer** [comment]
Uninstall that version. 
Try the latest version  https://github.com/drewcifer/bot-topia/releases/latest

[v1.0.7](https://github.com/drewcifer/bot-topia/releases/download/v1.0.7/Bot-Topia.mcaddon)

If it's still not working uninstall and try installing the behavior pack and resource pack separately. If you do this be sure both packs are active on your world.
[BP Bot Topia](https://github.com/drewcifer/bot-topia/releases/download/v1.0.7/BP.Bot-Topia.mcpack)
[RP](https://github.com/drewcifer/bot-topia/releases/download/v1.0.7/BP.Bot-Topia.mcpack)

**Comment by crotin1111** [comment]
Still no result, I tried with both, it's the behavior pack giving the error but I can't seem to understand the issue

**Comment by drewcifer** [comment]
I see the warning error on my end. It's a dependency issue that I see a warning for. I'll have to look a little deeper to see how to resolve it.

**Comment by crotin1111** [comment]
It could be a lot of things but it also could be an add-on required inside to make it work via Xbox

**Comment by crotin1111** [comment]
@drewcifer this might be relevant?

https://bugs.mojang.com/browse/MCPE-38529
Seems to be a UUID issue but I'm not sure

**Comment by drewcifer** [comment]
yeah that's the one. so I'm on windows but I could see the warning and I noticed in the file path there was bot-topia(1) soon as I saw this I knew there must be a duplicate. I opened it in the file explorer and there were two bot topia resource packs. 

This maybe different on xbox I'm not sure. I went in to minecraft and uninstalled bot-topia completely. Then in file explorer I went into the directory that minecraft keeps all resource packs and deleted the two bot-topia folders. I did the same for behavior packs. 

Made sure the pack I was installing was the v1.0.7 of bot-topia. installed it by double clicking the file.
That resolved that issue.

it didn't matter how many times I updated or reinstalled until I removed those directories in the file explorer.
now there is a different warning that shows up. it has to do with the help menu and should not prevent the addon from working.

**Comment by crotin1111** [comment]
@drewcifer let me know when it's solved I'm so excited to help in some ways and I'm so excited to use it!!

**Comment by drewcifer** [comment]
So after further investigating the UUID dependency is a known error. It's now a real error minecraft just flags it as an error. So this is something on Mojang's end. 

Like I said with v1.0.7 of Bot-Topia the error is gone. The only way I could properly update was to go into the file explorer and navigate to where minecraft keeps the behavior and resource packs that are installed and delete bot topia manually. After you do that you can install the latest version of bot topia and it should be all good.

**Comment by drewcifer** [comment]
This is what you can do. In minecraft go to settings then go to storage. Remove bot-topia behavior pack and resource pack.
go to your world you where using bot topia. click the edit icon. now deactivate the bot topia behavior and resource packs from there. Now you can install the new version of bot topia. You should be all go from there.

**Comment by drewcifer** [comment]
You can also use this guide. 

www.youtube.com/watch?v=754amkN3dok

It even covers how to fully remove broken addons. hope it helps.
